Fix statup error - missing package
Error: You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!